title = 'Learning Rust'
baseURL = 'https://learning-rust.github.io/'

defaultContentLanguage = 'en'
languageCode = 'en-us'

enableGitInfo = true

theme = 'docura'

markup.highlight.noClasses = false

[services]
[services.googleAnalytics]
ID = 'G-FZHQCXSZ89'